version: "3.9"

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.20-alpine
    env_file:
      - .dev.env
    ports:
      - "8080:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - nginx-shared:/nginx
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    env_file:
      - .dev.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "${POSTGRES_PORT}:5432"
  web:
    build: .
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT}
    env_file:
      - .dev.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
